### PR TITLE
fix(select): handle `null` & `undefined` as default values

### LINKED ISSUE #178: [ASelect]: Component broken when initial value is undefined
### What is actually happening?
```vue
<script setup lang="ts">
const selectedFruit = ref()
const fruits = ['banana', 'apple', 'watermelon', 'orange']
</script>

<template>
  <ASelect :options="fruits"/>
</template>
```
`ASelect`  is not rendered correctly when the modelValue is not passed or is undefined.
### What is Expected?
should render correctly

### PR DESCRIPTION
**Pull request by IcetCode**
fix #178

### CODE REVIEW

File: packages/anu-vue/src/components/select/ASelect.vue [hunk 1]
```diff
@@ -107,7 +115,7 @@ function middleware() {
         ref="selectRef"
         readonly
         class="a-select-input cursor-pointer"
-        :value="modelValue.text ?? modelValue"
+        :value="selectedValueText"
```
Comment (jd-solanki) [inline packages/anu-vue/src/components/select/ASelect.vue:118]: What if we change it to `modelValue ? (modelValue.text ?? modelValue) : undefined`

I guess this will probably work the same as the new changes but with less code

File: packages/anu-vue/test/setup.vitest.ts [hunk 2]
```diff
@@ -1,7 +1,10 @@
-import { afterAll, beforeAll } from 'vitest'
+import { afterAll, beforeAll, vi } from 'vitest'
 import { createApp } from 'vue'
+import ResizeObserver from 'resize-observer-polyfill'
 import { plugin } from '../src/plugin'
 
+vi.stubGlobal('ResizeObserver', ResizeObserver)
```
Comment (jd-solanki) [inline packages/anu-vue/test/setup.vitest.ts:6]: Why do we need this, I probably seen this somewhere before 🤔 ?

Comment (IcetCode) [reply packages/anu-vue/test/setup.vitest.ts:6]: floating-ui depends on this API, but it does not exist in the Node.js environment.

File: packages/anu-vue/src/components/select/ASelect.vue (hunk 1 above)
Comment (IcetCode) [reply packages/anu-vue/src/components/select/ASelect.vue:118]: Yep,it can be changed to this, I do this just for readability.

Comment (jd-solanki) [reply packages/anu-vue/src/components/select/ASelect.vue:118]: Hey @IcetCode Can you please use `props.modelValue` instead of direct use of `modelValue` for future compatibility in template block? Anu defaults requires using `props.x` in template block.

Comment (IcetCode) [reply packages/anu-vue/src/components/select/ASelect.vue:118]: like this?
```ts
 :value="props.modelValue ? props.modelValue.text ?? props.modelValue : undefined"
```

Comment (jd-solanki) [reply packages/anu-vue/src/components/select/ASelect.vue:118]: Yes 💯

**Comment by jd-solanki** [comment]
Thanks 😇
